# openapi2-run.yaml
swagger: '2.0'
info:
  title: echo API
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://echo-api-6xgkyezkbq-km.a.run.app/
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/nick-learning-322807"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "nick-learning-322807"
paths:
  /:
    get:
      parameters:
        - in: path
          name: echo
          type: string
          required: true
          description: echo string to return
      summary: echo
      operationId: getEcho
      security:
        - firebase: [ ]
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              echo:
                type: "string"
    options:
      summary: echo options
      operationId: optionsEcho
      responses:
        '200':
          description: A successful response

